### ISSUE TITLE
Can't download multiple file contracts?

### ISSUE THREAD

**Issue by je37493149** [degensean/vscode-contract-code-viewer#1]
Hey man, this extension is really cool, but when I used it to download multiple file contracts, only `contractInfo.json` is downloaded. Could you please tell me why？
The contract is https://bscscan.com/address/0x13f816511384d3534783241ddb5751c4b7a7e148#code

**Comment by degensean** [comment]
Hi, please update the extension to v1.1.7. The problem has been fixed. Enjoy!

**Comment by degensean** [comment]
v1.1.9 is the latest version

> Hi, please update the extension to v1.1.7. The problem has been fixed. Enjoy!
